name: Update UniStore and pages

on:
  push:
    branches: [ master ]
    paths: [ generate.py, bannergif.py, "_nds/TWiLightMenu/*menu/themes/**", "_nds/TWiLightMenu/unlaunch/backgrounds/**", "_nds/TWiLightMenu/unlaunch/extras/fonts/**", "_nds/TWiLightMenu/icons/**", .github/workflows/update.yml ]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install packages
      run: |
        echo deb http://deb.debian.org/debian stable main contrib non-free >> /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get install python3-pip -y
        pip3 install -r requirements.txt

    - name: Delete old pages
      run: rm -rf docs/_nintendo-3ds/* docs/_nintendo-dsi/* docs/_r4-original/* docs/_wood-ui/* docs/_unlaunch/* docs/nintendo-3ds/category/* docs/nintendo-dsi/category/* docs/r4-original/category/* docs/wood-ui/category/* docs/unlaunch/category/*

    - name: Run generate.py
      run: |
        export PATH=$PATH:/opt/devkitpro/tools/bin
        python3 generate.py ${{ secrets.GITHUB_TOKEN }}

    - name: Push changes
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'Update UniStore and pages'
        force-add: 'false'
        files: '*'
        name: TWLBot
        email: flamekat54@aol.com 
